"""
ORCA-adapted replacement for Generate_energy_CSV_from_OSZICAR_SPDFT / Generate_geoms_CSV_from_POSCAR_SPDFT.

Reads the ~/orca_runs/spdft_jobs/type{N}_geom{NN}/job.{inp,out} single-point jobs
(generated by gen_spdft_jobs.py from the confirmed-Rotatable POSCAR geometries)
and writes SAVESTEPS-format {Material}_E_SPDFT.csv / {Material}_geoms_SPDFT.csv,
one row per atom per geometry (Cartesian Angstrom), energies in eV, ordered to
match RD_type index / instance numbering expected by Step 6.

Job ordering: SAVESTEPS expects one CSV per rotatable-dihedral *type*, with rows
for consecutive instances (1..36) within that type stacked in the geoms file and
one energy per instance in the E file. We reproduce that: one pair of CSVs per
type folder (type0, type2, type3), named GEMCIT_RDtype{N}_E_SPDFT.csv /
GEMCIT_RDtype{N}_geoms_SPDFT.csv.
"""
import os
import csv
import re

HARTREE_TO_EV = 27.211386245988

JOBS_DIR = os.path.expanduser("~/orca_runs/spdft_jobs")
OUT_DIR = os.path.expanduser("~/orca_runs/spdft_parsed")
MATERIAL = "GEMCIT"
TYPE_FOLDERS = ["0", "2", "3"]


def parse_energy_hartree(job_out_path):
    energy = None
    with open(job_out_path) as f:
        for line in f:
            if "FINAL SINGLE POINT ENERGY" in line:
                parts = line.split()
                energy = float(parts[-1])
    if energy is None:
        raise ValueError(f"No FINAL SINGLE POINT ENERGY found in {job_out_path}")
    return energy


def parse_coords_from_inp(job_inp_path):
    with open(job_inp_path) as f:
        lines = f.readlines()
    coords = []
    in_block = False
    for line in lines:
        if line.strip().startswith("* xyz"):
            in_block = True
            continue
        if in_block:
            if line.strip() == "*":
                break
            parts = line.split()
            coords.append((parts[0], float(parts[1]), float(parts[2]), float(parts[3])))
    return coords


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for type_folder in TYPE_FOLDERS:
        geom_dirs = sorted(
            (d for d in os.listdir(JOBS_DIR) if d.startswith(f"type{type_folder}_geom")),
            key=lambda d: int(re.search(r"geom(\d+)", d).group(1)),
        )
        if not geom_dirs:
            print(f"WARNING: no jobs found for type{type_folder}")
            continue

        e_csv_path = os.path.join(OUT_DIR, f"{MATERIAL}_RDtype{type_folder}_E_SPDFT.csv")
        geoms_csv_path = os.path.join(OUT_DIR, f"{MATERIAL}_RDtype{type_folder}_geoms_SPDFT.csv")

        with open(e_csv_path, "w", newline="") as ef, open(geoms_csv_path, "w", newline="") as gf:
            e_writer = csv.writer(ef)
            g_writer = csv.writer(gf)
            n_atoms_ref = None
            for gd in geom_dirs:
                job_dir = os.path.join(JOBS_DIR, gd)
                status_path = os.path.join(job_dir, "STATUS")
                if not os.path.exists(status_path) or open(status_path).read().strip() != "0":
                    print(f"WARNING: {gd} missing or non-zero STATUS, skipping")
                    continue
                energy_ha = parse_energy_hartree(os.path.join(job_dir, "job.out"))
                e_writer.writerow([energy_ha * HARTREE_TO_EV])

                coords = parse_coords_from_inp(os.path.join(job_dir, "job.inp"))
                if n_atoms_ref is None:
                    n_atoms_ref = len(coords)
                elif len(coords) != n_atoms_ref:
                    raise ValueError(f"{gd}: atom count {len(coords)} != {n_atoms_ref}")
                for sym, x, y, z in coords:
                    g_writer.writerow([x, y, z])

        print(f"type{type_folder}: {len(geom_dirs)} geoms -> {e_csv_path}, {geoms_csv_path}")


if __name__ == "__main__":
    main()
